[package]
name = "basic-adder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.13.1"
thiserror = "1.0.24"
arrayref = "0.3.6"
borsh = "0.9.3"

[lib]
crate-type = ["cdylib", "lib"]